version: "3"
services:
    db:
        image: postgres
        restart: unless-stopped
        networks: 
            - "pynet"
        env_file: 
            - "secrets.env"
    
    api:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
            args:
                VARIANT: 3.8
        volumes: 
            - ..:/workspace
        networks: 
            - "pynet"
        ports:
            - "8080:8000"   
        env_file: 
            - "secrets.env"
        
        command: sleep infinity


networks:
    pynet: